export const UPDATE_SENSOR_1_TEMP = "UPDATE_SENSOR_1_TEMP";
export const UPDATE_SENSOR_2_TEMP = "UPDATE_SENSOR_2_TEMP";
export const UPDATE_SENSOR_3_TEMP = "UPDATE_SENSOR_3_TEMP";
export const UPDATE_TEMPERATURE_UNITS = "UPDATE_TEMPERATURE_UNITS";
export const UPDATE_DEMO_MODE = "UPDATE_DEMO_MODE";