// Temperature
export const UPDATE_SENSOR_TEMPERATURE = "UPDATE_SENSOR_TEMPERATURE";
export const UPDATE_HIGH_ALARM = "UPDATE_HIGH_ALARM";
export const UPDATE_HIGH_ALARM_ACTIVE = "UPDATE_HIGH_ALARM_ACTIVE";
export const UPDATE_LOW_ALARM = "UPDATE_LOW_ALARM";
export const UPDATE_LOW_ALARM_ACTIVE = "UPDATE_LOW_ALARM_ACTIVE";

// Settings
export const UPDATE_TEMPERATURE_UNITS = "UPDATE_TEMPERATURE_UNITS";
export const UPDATE_DEMO_MODE = "UPDATE_DEMO_MODE";
export const UPDATE_REFRESH_RATE = "UPDATE_REFRESH_RATE";
