export const UPDATE_SENSOR_TEMPERATURE = "UPDATE_SENSOR_TEMPERATURE";
export const UPDATE_TEMPERATURE_UNITS = "UPDATE_TEMPERATURE_UNITS";
export const UPDATE_DEMO_MODE = "UPDATE_DEMO_MODE";
export const UPDATE_REFRESH_RATE = "UPDATE_REFRESH_RATE";
